import { Injectable } from '@nestjs/common';
import { Resend } from 'resend';

type PlacementDriveEmailData = {
  companyName?: string;
  driveName?: string;
  jobLocation?: string | null;
  jobDescriptionUrl?: string | null;
  companyApplyUrl?: string | null;
  minCgpa?: number | null;
  maxBacklog?: number | null;
  startDate?: string | Date | null;
  registrationDeadline?: string | Date | null;
  regDeadline?: string | Date | null;
};


@Injectable()
export class NotificationsService {
    private readonly resend: Resend;

  constructor() {
    this.resend = new Resend(process.env.RESEND);
  }

    async sendEmail(email: string, companyData: PlacementDriveEmailData) {

    const companyName = companyData.companyName ?? companyData.driveName ?? 'New company';
    const escapeHtml = (value: string) => value
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');
    const formatDate = (value: string | Date | null | undefined) => value
      ? new Date(value).toLocaleDateString('en-IN', {
        day: '2-digit',
        month: 'short',
        year: 'numeric',
      })
      : 'Not specified';
    const detail = (label: string, value: string) => `<p><strong>${label}:</strong> ${escapeHtml(value)}</p>`;
    const jobDescription = companyData.jobDescriptionUrl
      ? `<p><a href="${escapeHtml(companyData.jobDescriptionUrl)}">View job description</a></p>`
      : '';
    const applyLink = companyData.companyApplyUrl
      ? `<p><a href="${escapeHtml(companyData.companyApplyUrl)}">Apply for this placement drive</a></p>`
      : '';

    const { data, error } = await this.resend.emails.send({
      from: `${process.env.SENDER_EMAIL}`,
      to: `${email}`,
      subject: `New Placement Drive: ${companyName}`,
      html: `
        <h2>New Placement Drive</h2>

        <p>A new placement opportunity is available.</p>
        ${detail('Company', companyName)}
        ${detail('Location', companyData.jobLocation ?? 'Not specified')}
        ${detail('Minimum CGPA', companyData.minCgpa?.toString() ?? 'Not specified')}
        ${detail('Maximum Backlogs', companyData.maxBacklog?.toString() ?? 'Not specified')}
        ${detail('Drive date', formatDate(companyData.startDate))}
        ${detail('Registration deadline', formatDate(companyData.registrationDeadline ?? companyData.regDeadline))}
        ${jobDescription}
        ${applyLink}

        <br>

        <hr>
        <p><small>This email is not generated by the official Carrier Development Cell. For any concerns, contact rajputkrishuuu@gmail.com.</small></p>
      `,
    });

    if (error) {
      console.error(error);
      return;
    }

    console.log('Email sent:', data);
  }

}
